Feat/51590
voidagency/vactory_starter_kit pull request #676
Opened 2024-06-03 10:39 UTC by ismail-void

2024-06-04 12:27 UTC, Bahlaouane-Hamza requested changes

2024-06-04 12:27 UTC, Bahlaouane-Hamza commented on composer.json
> +        "Registered claims error after upgrading from 5.0.5 to 5.2.0": "https://gist.githubusercontent.com/ismail-void/539733588565017233ef8d26907823df/raw/6eeeb0cdc770a3d6a0d4e643b8b0b5d0319c31c2/fi
@ismail-void 
voici les patches void
https://gist.githubusercontent.com/voidagency/50a350247c84e74cd0bdfb788f1ddcc0/raw/a9fba4fe002542bc1f43742a83965ddeaa3eaba8/fix-registered-claims-error.patch
https://gist.githubusercontent.com/voidagency/fc4c7543f6bcd53d0f12ac4bb499aa77/raw/3a84f6cd17b3b02c42c5ea830d45b06eb3a0c3be/jwks-endpoint-accessible-without-authentication.patch

2024-06-04 12:27 UTC, Bahlaouane-Hamza commented on modules/vactory_decoupled/vactory_decoupled.module
> +        ->accessCheck('FALSE')
Pas de soucis côté lang ?

2024-06-06 09:09 UTC, ismail-void commented on modules/vactory_decoupled/vactory_decoupled.module
> +        ->accessCheck('FALSE')
@Bahlaouane-Hamza 
- Le filtre par langcode n'est pas vraiment nécessaire, car la dernière version (traduction) enregistrée est toujours la dernière révision.
- Je l'ai ajouté par précaution.

2024-06-06 09:16 UTC, merged